
server {
	listen 443 ssl;
	# server_name edraccan-transcendence.duckdns.org;
	listen [::]:443 ssl;

	error_page 497 https://$host:8000$request_uri;

	access_log off;
	error_log /dev/null crit;

	http2 on;

	ssl_certificate_key     /etc/nginx/ssl/server.key;
    ssl_certificate 		/etc/nginx/ssl/server.crt;

	# SSL PROTOCOL
	ssl_protocols TLSv1.2 TLSv1.3; # only TLSv1.3
	ssl_prefer_server_ciphers off; # disable choosing of chiphrature, TLSv1.3 manages it by itself

	# WAF (ModSecurity Module)
	modsecurity on;
	modsecurity_rules_file /etc/nginx/modsecurity/main.conf;

	location ~ ^/(@vite|@id|virtual:|node_modules/\.vite) {
		modsecurity off;
		proxy_pass http://frontend:5173;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
	}

	location / {
        # root /usr/share/nginx/html; # cartella base da cui nginx riprenderà i file dentro dist/ generati da vite build
		# try_files $uri $uri/ /index.html;
		# prova prima a servire il file richiesto esattamente com'è ($uri), poi prova come cartella ($uri/), altrimenti fai fallback su index.html
		#Questo fallback è essenziale per le Single Page App con Vue Router in modalità history: se l'utente ricarica su /profile/42,
		#quel path non esiste come file fisico, e senza questa riga nginx risponderebbe 404.
		#Con questa riga, invece, serve comunque index.html, e Vue Router (lato client) si occupa di mostrare la pagina giusta.
		proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
	}

	location /@vite/client { # endpoint che Vite usa lato client per il canale HMR (file JS nell'HTML che apre la connessione websocket)
	# si usano stesse righe di / così da garantire upgrade anche in caso di cambio alla location /
		proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
	}

	location /api/ {
		proxy_pass http://backend:8080;
		proxy_set_header Host $host;
	}

	location /auth/ {
		proxy_pass http://backend:8080;
		proxy_set_header Host $http_host;
	}

	location /socket.io/ {
		modsecurity off;
		proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; # questa volta non per Vite ma per la comunicazione tra client e server
	}

	location /media/ {
		proxy_pass http://backend:8080/media/;
		proxy_set_header Host $host;
	}
}