# Config base ModSecurity (motore, log, limiti body)
Include /etc/nginx/modsecurity/modsecurity.conf

# Regole generali CRS (esclusioni, ip ecc.)
Include /etc/nginx/modsecurity/crs/crs-setup.conf
SecAction \
 "id:900000,\
  phase:1,\
  pass,\
  t:none,\
  nolog,\
  setvar:tx.paranoia_level=1,\
  setvar:tx.inbound_anomaly_score_threshold=5,\
  setvar:tx.outbound_anomaly_score_threshold=7"
# phase -> paranoia level (PL) ovvero quanto è strict ModSecurity per le richieste (più alto = più falsi positivi da gestire)
# inbound_anomaly_score_threshold -> soglia di punteggio che blocca le richieste (5 -> standard, 7-10 più permissivo)
# outbound_anomaly_score_threshold -> uguale a sopra ma per le risposte (controlla non vengano leakkati dati sensibili)

SecAction \
 "id:900200,\
  phase:1,\
  pass,\
  t:none,\
  nolog,\
  setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE PATCH'"

# Caricamento delle regole vere e proprie
Include /etc/nginx/modsecurity/crs/rules/*.conf